# Kernel SVM

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [69]:
dataset = pd.read_csv('Airbag_Must_Rec_No.csv')
X = dataset.iloc[:, [0,1,2,3,4]].values
y = dataset.iloc[:, 7].values

In [70]:
print(X)

[[  1.      0.     20.     39.27   69.82 ]
 [  1.     15.     20.     21.51   38.19 ]
 [  1.     30.     20.      7.413  14.05 ]
 ...
 [ -7.     75.     70.    498.3   893.6  ]
 [ -7.    -15.     70.     66.4    77.76 ]
 [ -7.    -30.     70.     29.8    54.2  ]]


In [71]:
print(y)

['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'Recommended' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'Recommended' 'No' 'No' 'No' 'No' 'No' 'Recommended' 'No'
 'No' 'No' 'No' 'Recommended' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 

In [72]:
## encoding y variables 

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1
 2 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1
 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 0 0 0 1 1 1 0 0 2 1 1 0 0 2 1 1 1 0 2 2 1 1 0 0 0 1 1 1 2 0 2 1 1 2
 0 2 1 1 1 2 2 2 1 1 2 2 2 1 1 1 1 1 1 1 1 1 2 1 1 1 0 1 1 0 1 1 1 1 1 0 1
 0 0 0 2 1 1 0 1 1 1 1 0 0 0 2 2 1 2 2 1 1 1 0 0 0 2 2 1 2 1 1 1 1 2 0 0 2
 2 1 1 1 1 1 2 2 2 2 1 1 2 1 1 0 2 1 1 1 1 1 1 0 0 0 0 1 1 0 0 0 2 2 0 0 0
 0 1 1 0 0 0 0 2 0 0 0 0 0 1 0 0 0 2 2 0 0 0 1 0 1 0 0 0 2 2 0 0 0 0 0 1 0
 0 2 2 0 0 0 0 1 1 0 0 1 0 1 0 1 1 1 1 1 0 0 0 0 0 2 0 2 0 1 1 0 0 0 0 2 2
 0 0 0 1 1 0 0 0 0 0 2 0 

## Splitting the dataset into the Training set and Test set

In [73]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y , test_size = 0.25 , random_state = 0)


In [74]:
print(X_train)


[[-3.000e+00  0.000e+00  6.000e+01  4.277e+03  4.277e+03]
 [ 6.000e+00 -4.500e+01  2.000e+01  5.720e+00  1.217e+01]
 [-2.000e+00 -3.000e+01  2.000e+01  9.138e+00  1.709e+01]
 ...
 [-5.000e+00  3.000e+01  6.000e+01  6.586e+03  6.586e+03]
 [ 4.000e+00  4.500e+01  6.000e+01  4.651e+03  5.717e+03]
 [ 3.000e+00 -6.000e+01  7.000e+01  1.866e+04  2.254e+04]]


In [75]:
print(X_test)


[[-6.000e+00 -1.500e+01  4.000e+01  6.508e+01  1.051e+02]
 [-4.000e+00  1.500e+01  5.000e+01  1.347e+04  1.861e+04]
 [-3.000e+00 -3.000e+01  4.000e+01  1.113e+02  1.686e+02]
 [ 2.000e+00  4.500e+01  2.000e+01  6.085e+00  1.349e+01]
 [ 2.000e+00  4.500e+01  3.000e+01  1.020e+02  1.458e+02]
 [ 3.000e+00 -3.000e+01  5.000e+01  5.290e+03  5.290e+03]
 [-4.000e+00 -6.000e+01  7.000e+01  8.958e+03  8.958e+03]
 [-6.000e+00 -4.500e+01  3.000e+01  6.968e+00  1.266e+01]
 [ 5.000e+00  0.000e+00  3.000e+01  1.017e+02  1.163e+02]
 [-4.000e+00 -3.000e+01  3.000e+01  1.179e+01  2.309e+01]
 [ 3.000e+00 -6.000e+01  2.000e+01  5.721e+00  7.988e+00]
 [-5.000e+00  0.000e+00  3.000e+01  1.687e+01  3.630e+01]
 [-7.000e+00  4.500e+01  7.000e+01  4.512e+02  7.294e+02]
 [ 4.000e+00 -3.000e+01  6.000e+01  9.253e+03  9.306e+03]
 [ 3.000e+00  4.500e+01  3.000e+01  2.532e+02  3.635e+02]
 [-3.000e+00  3.000e+01  3.000e+01  6.719e+01  1.013e+02]
 [ 5.000e+00  6.000e+01  5.000e+01  6.984e+03  6.984e+03]
 [ 4.000e+00 -

In [76]:
print(y_train)

[0 1 1 1 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 0 1 0 1 1 0 1 0 1 1 0 0 0
 0 0 1 0 1 1 1 1 1 1 0 0 1 2 0 0 1 1 1 1 0 1 1 0 1 2 1 1 1 1 1 2 0 2 0 0 1
 0 0 0 0 0 0 1 1 2 1 0 1 1 0 0 0 1 0 0 0 1 2 1 1 0 1 1 0 1 0 1 1 1 1 0 0 1
 0 1 0 0 0 1 1 1 1 1 1 0 0 1 1 0 1 0 1 0 1 2 2 0 1 0 2 1 1 0 0 2 1 1 2 0 0
 0 1 1 0 1 1 0 2 0 0 0 0 2 0 1 1 1 0 0 0 0 1 0 1 1 0 0 1 2 0 1 1 1 1 1 2 0
 0 0 0 1 0 1 1 1 1 0 1 1 0 1 2 1 0 2 1 1 0 0 1 2 2 0 1 0 1 0 1 2 0 0 0 0 0
 1 1 0 0 1 1 0 0 0 1 1 0 0 1 1 1 2 1 2 1 0 0 1 1 1 1 0 1 0 1 1 1 0 0 2 0 0
 1 0 2 1 1 1 2 0 1 1 0 1 0 0 0 1 1 0 0 1 0 2 0 1 0 0 1 0 0 2 0 0 2 1 1 0 1
 0 1 1 1 0 1 2 1 0 0 1 0 1 2 0 0 0 0 0 1 1 1 1 1 0 1 2 0 0 0 1 1 0 1 0 0 2
 0 0 0 0 0 1 1 0 1 1 0 1 1 1 1 0 0 0 1 1 2 2 1 0 0 0 1 1 2 1 1 0 2 0 0 1 1
 1 1 1 1 0 1 1 2 0 2 1 0 0 0 0 0 0 2 1 1 0 0 1 1 0 0 0 0 1 1 1 1 1 1 1 1 1
 1 0 0 0 0 1 0 0 1 2 1 1 0 1 0 2 1 0 1 1 1 1 1 0 1 0 1 1 1 0 1 0 0 0 1 1 0
 0 1 1 2 0 2 0 0 0 0 1 1 1 0 2 0 1 1 1 2 1 1 1 1 1 1 0 0 1 2 0 1 0 1 2 1 1
 0 2 2 2 1 1 0 0 0 1 2 1 

In [77]:
print(y_test)


[2 0 2 1 1 0 0 1 1 1 1 1 0 0 1 1 0 2 1 2 1 0 0 0 1 2 0 0 1 2 0 0 1 0 2 0 1
 1 0 1 1 1 0 1 0 1 0 1 1 1 0 1 2 1 0 1 1 0 0 1 1 1 0 0 0 1 1 0 1 0 2 0 0 0
 2 1 0 0 1 0 1 0 2 0 0 1 1 0 1 2 0 1 1 2 0 1 2 2 1 1 0 0 0 0 1 2 1 0 0 1 2
 1 1 1 1 0 1 2 1 1 1 1 2 1 0 0 1 1 2 1 1 1 0 1 1 0 1 1 1 2 1 1 1 0 1 0 1 1
 1 1 1 1 1 0 1 2 0 0 2 0 2 2 0 0 1 1 1 0 0 2 1 2 1 0 0 1 0 0 0 0 1 0 1 1 2
 0 0 0 1 0 1 1 1 2 1 1]


## Feature Scaling

In [78]:
from sklearn.preprocessing import StandardScaler
sc =StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [79]:
print(X_train)

[[-0.73816935 -0.18189994  0.87643187  0.146386    0.11384353]
 [ 1.31407374 -1.18121275 -1.46071979 -0.50715253 -0.52368979]
 [-0.51014234 -0.84810848 -1.46071979 -0.50662955 -0.52295432]
 ...
 [-1.19422336  0.4843086   0.87643187  0.49968067  0.45900721]
 [ 0.85801972  0.81741287  0.87643187  0.20361086  0.32910368]
 [ 0.62999271 -1.51431702  1.46071979  2.34709506  2.84391038]]


In [80]:
print(X_test)

[[-1.42225037e+00 -5.15004212e-01 -2.92143958e-01 -4.98069992e-01
  -5.09798038e-01]
 [-9.66196355e-01  1.51204327e-01  2.92143958e-01  1.55298534e+00
   2.25642953e+00]
 [-7.38169345e-01 -8.48108482e-01 -2.92143958e-01 -4.90997978e-01
  -5.00305663e-01]
 [ 4.01965700e-01  8.17412866e-01 -1.46071979e+00 -5.07096678e-01
  -5.23492471e-01]
 [ 4.01965700e-01  8.17412866e-01 -8.76431873e-01 -4.92420949e-01
  -5.03713949e-01]
 [ 6.29992710e-01 -8.48108482e-01  2.92143958e-01  3.01382749e-01
   2.65273068e-01]
 [-9.66196355e-01 -1.51431702e+00  1.46071979e+00  8.62614817e-01
   8.13588526e-01]
 [-1.42225037e+00 -1.18121275e+00 -8.76431873e-01 -5.06961572e-01
  -5.23616545e-01]
 [ 1.08604673e+00 -1.81899942e-01 -8.76431873e-01 -4.92466852e-01
  -5.08123793e-01]
 [-9.66196355e-01 -8.48108482e-01 -8.76431873e-01 -5.06223770e-01
  -5.22057403e-01]
 [ 6.29992710e-01 -1.51431702e+00 -1.46071979e+00 -5.07152373e-01
  -5.24314944e-01]
 [-1.19422336e+00 -1.81899942e-01 -8.76431873e-01 -5.05446491e-01

## Training the Kernel SVM model on the Training set

In [81]:
from sklearn.svm import SVC 
classifier =  SVC(C =4, kernel = 'rbf', gamma='scale', random_state = 0, cache_size= 100, decision_function_shape ='ovo', max_iter=-1)
classifier.fit(X_train,y_train)


SVC(C=4, cache_size=100, decision_function_shape='ovo', random_state=0)

## XG **Boost**

In [82]:
# from xgboost import XGBClassifier
# classifier = XGBClassifier()
# classifier.fit(X_train, y_train)

## Predict a New Result

In [83]:

# y_predict = print(classifier.predict(sc.transform([[50,61,0]])))

# print(dataset.iloc[11,1:-2].values)

## Prediction a data and Comparison

In [84]:
# y_pred = classifier.predict(X_test)

# print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Making the Confusion Matrix

In [85]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[67  2  3]
 [ 6 86  3]
 [ 4  8 17]]


0.8673469387755102

## K Fold cross validation score


In [86]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

accuracies = cross_val_score(estimator=classifier, X = X_train, y=y_train, cv=10)
print('accuracies: {:2f} %'.format(accuracies.mean()*100))
print('Standard Deviation: {:2f}%'.format(accuracies.std()*100))

accuracies: 89.754530 %
Standard Deviation: 2.187184%


## Applying grid search to find the best model and best performance


In [65]:

# from sklearn.model_selection import GridSearchCV
# parameters = [{'C':range(1,5,1), 
#                'kernel':['rbf'],
#                'gamma':['scale','auto'],
#                'cache_size':[100,200,300,400,500],
#                'decision_function_shape':['ovo', 'ovr'],
#                'random_state': range(0,5,1),
#                'max_iter': [-1,0,1]
#               }]

# grid_search = GridSearchCV(estimator=classifier, 
#                            param_grid = parameters, 
#                            scoring='accuracy', 
#                            n_jobs=-1, 
#                            cv = 10)
# grid_search.fit(X_train,y_train)
# best_accuracy = grid_search.best_score_
# best_parameters =grid_search.best_params_
# print('Best accuracies: {:2f} %'.format(best_accuracy*100))
# print('Best parameters:',best_parameters)





In [87]:
# from matplotlib.colors import ListedColormap
# X_set, y_set = sc.inverse_transform(X_train), y_train
# X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - -10, stop = X_set[:, 0].max() + 10, step = 0.25),
#                      np.arange(start = X_set[:, 1].min() - -100, stop = X_set[:, 1].max() + 100, step = 0.25))
# #                          ,
# #                     np.arange(start = X_set[:,2].min() - 20, stop = X_set[:,2].max() + 20, step = 0.25))
# plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
#              alpha = 0.75, cmap = ListedColormap(('red', 'green','yellow')))
# plt.xlim(X1.min(), X1.max())
# plt.ylim(X2.min(), X2.max())
# # plt.zlim(X3.min(),X3.max())
# for i, j in enumerate(np.unique(y_set)):
#     plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green','yellow'))(i), label = j)
# plt.title('Kernel SVM (Training set)')
# plt.xlabel('Age')
# plt.ylabel('Estimated Salary')
# plt.legend()
# plt.show()