# Support Vector Machine (SVM)

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('Airbag_Must_Rec_No.csv')
X = dataset.iloc[:, [0,1,2,3,4]].values
y = dataset.iloc[:, 7].values

In [ ]:
print(X)


In [ ]:
print(y)

In [ ]:
## encoding y variables 

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
print(X_train)


In [ ]:
print(y_train)

In [ ]:
print(X_test)


In [ ]:
print(y_test)


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)


In [ ]:
print(X_test)


## Training the SVM model on the Training set

In [94]:
from sklearn.svm import LinearSVC
classifier = SVC(kernel='linear', random_state=0, C = 3, cache_size = 100, decision_function_shape = 'ovo', max_iter = -1)
classifier.fit(X_train, y_train)

SVC(C=3, cache_size=100, decision_function_shape='ovo', kernel='linear',
    random_state=0)

## XG Boost

In [95]:
# from xgboost import XGBClassifier
# classifier = XGBClassifier()
# classifier.fit(X_train, y_train)

## predicting a new result

In [96]:

# y_predict = print(classifier.predict(sc.transform([[50,61,0]])))

# print(dataset.iloc[11,1:-2].values)


## Prediction of data and Comparison 

In [97]:

# y_pred = classifier.predict(X_test)

# print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Making the Confusion Matrix

In [98]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

[[66  6  0]
 [ 8 87  0]
 [11 18  0]]
0.7806122448979592


## K Fold cross validation score




In [99]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

accuracies = cross_val_score(estimator=classifier, X = X_train, y=y_train, cv=10)
print('accuracies: {:2f} %'.format(accuracies.mean()*100))
print('Standard Deviation: {:2f}%'.format(accuracies.std()*100))

accuracies: 82.255991 %
Standard Deviation: 2.632760%


## Applying grid search to find the best model and best performance


In [ ]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C':range(0,5,1), 
               'kernel':['linear'],
               'cache_size':[100,200,300,400,500],
               'decision_function_shape':['ovo', 'ovr'],
               'random_state': range(0,5,1),
               'max_iter': [-1,0,1],}]
 
grid_search = GridSearchCV(estimator=classifier, 
                           param_grid = parameters, 
                           scoring='accuracy', 
                           n_jobs=-1, 
                           cv = 10)
grid_search.fit(X_train,y_train)
best_accuracy = grid_search.best_score_
best_parameters =grid_search.best_params_
print('Best accuracies: {:2f} %'.format(best_accuracy*100))
print('Best parameters:',best_parameters)

 ## Visualising the Training set results